// <auto-generated />
using MarketSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketSitesi.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20250906164932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketSitesi.Models.Icecek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Hacim")
                        .HasColumnType("int");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int");

                    b.Property<int>("YiyecekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YiyecekId");

                    b.ToTable("Icecekler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Gazlı içecek",
                            Ad = "Kola",
                            Fiyat = 5.50m,
                            Hacim = 330,
                            StokAdedi = 200,
                            YiyecekId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Doğal kaynak suyu",
                            Ad = "Su",
                            Fiyat = 2.00m,
                            Hacim = 500,
                            StokAdedi = 500,
                            YiyecekId = 2
                        });
                });

            modelBuilder.Entity("MarketSitesi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Et ve tavuk ürünleri",
                            Ad = "Et ve Tavuk"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Süt ve süt ürünleri",
                            Ad = "Süt Ürünleri"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Taze meyve ve sebzeler",
                            Ad = "Meyve ve Sebze"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Çeşitli içecekler",
                            Ad = "İçecekler"
                        });
                });

            modelBuilder.Entity("MarketSitesi.Models.Yiyecek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Yiyecekler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Taze tavuk göğsü",
                            Ad = "Tavuk Göğsü",
                            Fiyat = 45.50m,
                            KategoriId = 1,
                            StokAdedi = 20
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "1 litre tam yağlı süt",
                            Ad = "Süt",
                            Fiyat = 12.75m,
                            KategoriId = 2,
                            StokAdedi = 50
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Kırmızı elma",
                            Ad = "Elma",
                            Fiyat = 8.90m,
                            KategoriId = 3,
                            StokAdedi = 100
                        });
                });

            modelBuilder.Entity("MarketSitesi.Models.Icecek", b =>
                {
                    b.HasOne("MarketSitesi.Models.Yiyecek", "Yiyecek")
                        .WithMany("Icecekler")
                        .HasForeignKey("YiyecekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yiyecek");
                });

            modelBuilder.Entity("MarketSitesi.Models.Yiyecek", b =>
                {
                    b.HasOne("MarketSitesi.Models.Kategori", "Kategori")
                        .WithMany("Yiyecekler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("MarketSitesi.Models.Kategori", b =>
                {
                    b.Navigation("Yiyecekler");
                });

            modelBuilder.Entity("MarketSitesi.Models.Yiyecek", b =>
                {
                    b.Navigation("Icecekler");
                });
#pragma warning restore 612, 618
        }
    }
}
